[workspace]

members = [
    "rusty-workers-runtime",
    "rusty-workers-fetchd",
    "rusty-workers",
    "rusty-workers-cli",
    "rusty-workers-proxy",
    "rusty-workers-cp",
]

[profile.release]
debug = false

# Set panic=abort because Tokio does not terminate the program on panics.
panic = "abort"
