apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rusty-workers
  name: fetchd
  labels:
    app: fetchd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fetchd
  template:
    metadata:
      namespace: rusty-workers
      name: fetchd
      labels:
        app: fetchd
    spec:
      containers:
      - name: fetchd
        image: __IMAGE_PREFIX__rusty-workers-fetchd__IMAGE_SUFFIX__
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.1
            memory: 32Mi
        env:
        - name: RUST_LOG
          value: debug
        - name: RW_MAX_CONCURRENCY
          value: "1000"
        ports:
        - containerPort: 3000