apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: __NAMESPACE__
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      namespace: __NAMESPACE__
      name: proxy
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: __IMAGE_PREFIX__rusty-workers-proxy__IMAGE_SUFFIX__
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.1
            memory: 64Mi
        env:
        - name: RUST_LOG
          value: info
        - name: RW_CONFIG_URL
          value: __PROXY_CONFIG_URL__
        - name: RW_FETCH_SERVICE
          value: __NET_PREFIX__.3:3000
        - name: RW_MAX_IO_CONCURRENCY
          value: "10"
        - name: RW_MAX_IO_PER_REQUEST
          value: "50"
        - name: RW_MAX_MEMORY_MB
          value: "16"
        - name: RW_MAX_TIME_MS
          value: "200"
        - name: RUNTIMES
          value: __RUNTIME_ADDRESSES__
        ports:
        - containerPort: 8080
