apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: __NAMESPACE__
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      namespace: __NAMESPACE__
      name: proxy
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: __IMAGE_PREFIX__rusty-workers-proxy__IMAGE_SUFFIX__
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.1
            memory: 64Mi
        env:
        - name: RUST_LOG
          value: rusty_workers_proxy=info,rusty_workers=info
        - name: RW_FETCH_SERVICE
          value: __NET_PREFIX__.3:3000
        - name: RW_MAX_IO_CONCURRENCY
          value: "10"
        - name: RW_MAX_IO_PER_REQUEST
          value: "50"
        - name: RW_MAX_AB_MEMORY_MB
          value: "16"
        - name: RW_MAX_TIME_MS
          value: "200"
        - name: RUNTIMES
          # Query it 4 times when doing discovery
          value: __NET_PREFIX__.4:3000,__NET_PREFIX__.4:3000,__NET_PREFIX__.4:3000,__NET_PREFIX__.4:3000
        - name: RW_ROUTE_CACHE_SIZE
          value: "1000"
        - name: RW_APP_CACHE_SIZE
          value: "50"
        - name: RW_TIKV_CLUSTER
          value: "10.120.0.4:2379"
        ports:
        - containerPort: 8080
