apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: __NAMESPACE__
  name: runtime
  labels:
    app: runtime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: runtime
  template:
    metadata:
      namespace: __NAMESPACE__
      name: runtime
      labels:
        app: runtime
    spec:
      containers:
      - name: runtime
        image: __IMAGE_PREFIX__rusty-workers-runtime__IMAGE_SUFFIX__
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.6
            memory: 800Mi
          limits:
            # Enforce memory limit on runtime processes, in case v8 sandboxing failed to enforce it on isolate level.
            memory: 1000Mi
        env:
        - name: RUST_LOG
          value: info
        - name: RW_HIGH_MEMORY_THRESHOLD_BYTES
          value: "1073741824"
        - name: RW_MAX_NUM_OF_INSTANCES
          value: "50"
        - name: RW_MAX_CONCURRENT_REQUESTS
          value: "20"
        - name: RW_MAX_INACTIVE_TIME_MS
          value: "180000"
        ports:
        - containerPort: 3000
