apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rusty-workers
  name: runtime-X
  labels:
    app: runtime-X
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runtime-X
  template:
    metadata:
      namespace: rusty-workers
      name: runtime-X
      labels:
        app: runtime-X
    spec:
      containers:
      - name: runtime-X
        image: __IMAGE_PREFIX__rusty-workers-runtime__IMAGE_SUFFIX__
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 0.6
            memory: 800Mi
        env:
        - name: RUST_LOG
          value: debug
        - name: RW_HIGH_MEMORY_THRESHOLD_BYTES
          value: "1073741824"
        - name: RW_MAX_NUM_OF_INSTANCES
          value: "50"
        - name: RW_MAX_CONCURRENT_REQUESTS
          value: "20"
        - name: RW_MAX_INACTIVE_TIME_MS
          value: "180000"
        ports:
        - containerPort: 3000
