apiVersion: v1
kind: Service
metadata:
  namespace: __NAMESPACE__
  name: proxy-service
spec:
  selector:
    app: proxy
  externalIPs: __EXTERNAL_IPS__
  ports:
  - port: __EXTERNAL_PORT__
    targetPort: 8080
