name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build everything
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Install librt dependencies
        run: make librt-deps
      - name: Build Services
        run: make all
      - name: Build Docker Images
        run: make docker
      - name: Run Tests in Docker
        run: docker run --rm -e RUST_LOG=debug losfair/rusty-workers-all:latest
