name: build
on:
- push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install system dependencies
        run: sudo apt install libseccomp-dev
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.18.0
      - name: Install cargo-deb
        run: cargo install cargo-deb
      - name: Install jsland deps
        run: cd jsland && pnpm i
      - name: Build
        run: |
          BLUEBOAT_DEB=1 ./build.sh
          deb_file="$(find ./target/debian/ -type f)"
          cp ${deb_file} ./docker/blueboat.deb
      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./docker
          push: false
