on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build everything
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build Services
        run: make all
      - name: Build Docker Images
        run: make docker
